<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_login</name>
   <tag></tag>
   <elementGuidId>55834a7a-720d-48ef-bd1d-89590d1cacd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='anonLogin']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.grey</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82e3bcb3-e7fb-4d6a-964e-2306b0d68d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey</value>
      <webElementGuid>64b100cb-be88-4986-96c5-d8ff0439101b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ed9bb7a9-d6dd-419c-9275-83e32fd39c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-click</name>
      <type>Main</type>
      <value>gostr=/lzdpub.header.tbar;locaid=login</value>
      <webElementGuid>bfdebc25-8bb6-499d-81d6-b3bbcee0cd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4l.searchlistcategory.header.login</value>
      <webElementGuid>933483c2-46bf-4d33-9bff-283532697a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>a08c7355-a7b8-4d94-98d0-d9e7d0ee1229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anonLogin&quot;)/a[@class=&quot;grey&quot;]</value>
      <webElementGuid>ff23dca6-a904-4619-b5e1-3142f59c8868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='anonLogin']/a</value>
      <webElementGuid>e975c596-2e29-4147-9290-b9e6db79eb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'login')]</value>
      <webElementGuid>d10f4ef0-1dd8-4082-804d-d2c0ac3d1987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here'])[1]/following::a[1]</value>
      <webElementGuid>347c6563-984e-4dbb-a9e5-9f6f570f0968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your order number:'])[1]/following::a[2]</value>
      <webElementGuid>d7df22a0-65e0-4d74-b03a-b950b7f66632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='login']/parent::*</value>
      <webElementGuid>d45a036b-152a-426a-ad7e-9b24a8328d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>bdafc11c-fe8d-4ed9-8a21-525330d54e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>7b5140cd-bbb7-43cd-84e5-90012504a249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'login' or . = 'login')]</value>
      <webElementGuid>511a1260-0151-4dfc-b812-c9c5217dc231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
