<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Quantity</name>
   <tag></tag>
   <elementGuidId>5276ab01-8836-4f4b-8333-074f01da4d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='module_quantity-input']/div/h6</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pdp-mod-product-info-section.sku-quantity-selection > h6.section-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Quantity&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>d4a526dd-b934-4ed3-99fb-b8edb6c1cbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>d4f26164-74db-45f2-b21d-d983e667ce8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4l.pdp_revamp.0.i1.62d86b8865rBuv</value>
      <webElementGuid>f306fcbb-a1fd-4ab9-8f1d-4d9b7da0867d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity</value>
      <webElementGuid>910f463c-4cf5-4156-865e-c2f92ee9a095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module_quantity-input&quot;)/div[@class=&quot;pdp-mod-product-info-section sku-quantity-selection&quot;]/h6[@class=&quot;section-title&quot;]</value>
      <webElementGuid>bfbfa3b1-b7e7-4acd-9feb-4b0d42538494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='module_quantity-input']/div/h6</value>
      <webElementGuid>a71f705f-4d63-43b0-a96c-5e300b452635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feather-Random Color'])[1]/following::h6[1]</value>
      <webElementGuid>8f31a2c0-9234-40ab-86dc-ea0e9444d567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::h6[1]</value>
      <webElementGuid>d329e944-b371-4d04-896b-e3b2786835b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::h6[1]</value>
      <webElementGuid>90d869ee-4288-4bab-becd-9c683aaf9cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/preceding::h6[1]</value>
      <webElementGuid>31638e5a-24a6-4d92-85d1-815d6087c117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quantity']/parent::*</value>
      <webElementGuid>d1d5f246-2836-4459-8aa4-f9eede576859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/h6</value>
      <webElementGuid>e842b9b4-076f-4777-88d8-bd57c37424b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Quantity' or . = 'Quantity')]</value>
      <webElementGuid>525c302c-23bc-490b-a329-0c5fe3b579b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
