<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nice Cup Glass Bottle_cart-icon</name>
   <tag></tag>
   <elementGuidId>b11d136a-9cff-4893-8490-19ad70850320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topActionHeader']/div/div[2]/div/div[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.cart-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;120&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5a63ba0-b312-43cc-92c2-3b475ad1fc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-icon</value>
      <webElementGuid>a4a1f52f-9870-453c-b96f-1b707bf585a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4l.pdp_revamp.dcart.i0.10296b88FYLixj</value>
      <webElementGuid>3e78cea9-ea7c-42dd-ae77-754ae8d52376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topActionHeader&quot;)/div[@class=&quot;lzd-header-content&quot;]/div[@class=&quot;lzd-logo-bar default&quot;]/div[@class=&quot;logo-bar-content header-content&quot;]/div[@class=&quot;lzd-nav-cart&quot;]/a[1]/span[@class=&quot;cart-icon&quot;]</value>
      <webElementGuid>97750120-7c7f-4b8d-b7f3-cf9c4fdd0cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topActionHeader']/div/div[2]/div/div[3]/a/span</value>
      <webElementGuid>0dbd7e82-bd3a-4482-a98d-e19a51de0ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>1784c05f-1d83-45fa-864f-2deea0b4b291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
