<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PROCEED TO CHECKOUT(1)</name>
   <tag></tag>
   <elementGuidId>90265e99-521c-4c27-b124-2db5daf1ebde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.next-btn.next-btn-primary.next-btn-large.checkout-order-total-button.automation-checkout-order-total-button-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;PROCEED TO CHECKOUT(1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95b39722-cd31-47ac-b881-34ecbb299597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01b475f1-3a3f-4362-840c-862688c39da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next-btn next-btn-primary next-btn-large checkout-order-total-button automation-checkout-order-total-button-button</value>
      <webElementGuid>e26d4051-f65e-461d-80fa-c9746f17bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o42.cart.0.i4.26fc3e17VNzCpw</value>
      <webElementGuid>1e70af01-381b-44a6-acb9-d0bdff91309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PROCEED TO CHECKOUT(1)</value>
      <webElementGuid>f09b8025-0e33-42c5-b39a-e07737f5a52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightContainer_CR&quot;)/div[@class=&quot;summary-section&quot;]/div[@class=&quot;summary-section-content&quot;]/div[@class=&quot;checkout-summary&quot;]/div[@class=&quot;checkout-order-total&quot;]/button[@class=&quot;next-btn next-btn-primary next-btn-large checkout-order-total-button automation-checkout-order-total-button-button&quot;]</value>
      <webElementGuid>7be21041-e718-4618-a78a-37857ac235ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>927bbf03-b8f5-42e9-bbfc-632b8b6ab031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightContainer_CR']/div[2]/div[2]/div/div[3]/button</value>
      <webElementGuid>7f5bb96d-cb76-4518-8d23-27da92dd4fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VAT included, where applicable'])[1]/following::button[1]</value>
      <webElementGuid>72ffbc4d-0c3c-4db8-ba03-beed07676449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Care'])[1]/preceding::button[1]</value>
      <webElementGuid>94d8af1d-31ae-4b15-aa25-5b27ccd041e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help Center'])[1]/preceding::button[1]</value>
      <webElementGuid>97c504c8-2733-42ca-a6f9-1cc8dfebabbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCEED TO CHECKOUT(1)']/parent::*</value>
      <webElementGuid>6f63d465-35f5-4337-b2c3-6452139a1663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>9dc1ae7d-ac4d-4736-b433-f3dc9ef4e050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'PROCEED TO CHECKOUT(1)' or . = 'PROCEED TO CHECKOUT(1)')]</value>
      <webElementGuid>4cd5159e-74ca-4952-9792-caf412633ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
