<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product</name>
   <tag></tag>
   <elementGuidId>f373864b-ad62-4520-b75e-deefa7f14519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@type='product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[type=&quot;product&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cat Teaser Cat toy Imitation Birds Interactive Toy for Cats, Fun Feather with Bell, with Stick or Wand for Kittens&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>077d1abe-f704-4b7b-9db1-3e753916dca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>age</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c691e51c-5af8-4dd2-b524-109c7e6ddcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>a5076fb4-e8be-4bbf-a729-17f740e5e95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cat Teaser Cat toy Imitation Birds Interactive Toy for Cats, Fun Feather with Bell, with Stick or Wand for Kittens</value>
      <webElementGuid>e1ca82e9-4df3-4f82-a020-7a3fabcace3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.lazcdn.com/g/p/997c4b3fa68cd3a9bab87a87017a3770.jpg_200x200q80.jpg_.webp</value>
      <webElementGuid>1f6b5fac-f755-40ec-bf82-41ee285d0c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4l.searchlist.list.i40.8278319cDmQvaO</value>
      <webElementGuid>dc017c82-2eaf-4c1d-b712-abf5559ebd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;FWSEp&quot;]/div[@class=&quot;ant-row FrEdP css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-24 css-1bkhbmc app&quot;]/div[@class=&quot;ant-row css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-20 ant-col-push-4 Jv5R8 css-1bkhbmc app&quot;]/div[@class=&quot;_17mcb&quot;]/div[@class=&quot;Bm3ON&quot;]/div[@class=&quot;Ms6aG MefHh&quot;]/div[@class=&quot;qmXQo&quot;]/div[@class=&quot;ICdUp&quot;]/div[@class=&quot;_95X4G&quot;]/a[1]/div[@class=&quot;picture-wrapper jBwCF&quot;]/img[1]</value>
      <webElementGuid>49e4eec8-69b1-482c-b974-4bc4c1b128f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@type='product']</value>
      <webElementGuid>c38f29ca-6aad-4b63-97f8-76208fd529f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/div/div/div/div/a/div/img</value>
      <webElementGuid>f780d777-0dea-4280-8a2b-819c1f5dc2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cat Teaser Cat toy Imitation Birds Interactive Toy for Cats, Fun Feather with Bell, with Stick or Wand for Kittens']</value>
      <webElementGuid>b0527e07-44ef-4481-bd16-a2ab3156098b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>b6a483c5-1642-43ea-a1de-23fcecb1f0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@type = 'product' and @alt = 'Cat Teaser Cat toy Imitation Birds Interactive Toy for Cats, Fun Feather with Bell, with Stick or Wand for Kittens' and @src = 'https://img.lazcdn.com/g/p/997c4b3fa68cd3a9bab87a87017a3770.jpg_200x200q80.jpg_.webp']</value>
      <webElementGuid>ea305222-ad85-4fa3-8d94-b1aa01a50844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
