<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product_1</name>
   <tag></tag>
   <elementGuidId>28420da1-71c7-4b9c-86cf-e31d89ccfc6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@type='product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[type=&quot;product&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;1pc Pet Teaser Cat Toy Steel Wire Feather Interactive Cat Stick Training，Kitten Wand Toys with Beads Bells&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7785dcb9-5a79-42aa-852f-fa98a3b5f018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>age</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ffd70e12-470c-47dd-9e7c-779a04d23ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>958d32e5-520b-42a6-b7cf-d0d6376969ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>1pc Pet Teaser Cat Toy Steel Wire Feather Interactive Cat Stick Training，Kitten Wand Toys with Beads Bells</value>
      <webElementGuid>c6878f90-6d5a-446c-baf0-5fc6a90fafc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.lazcdn.com/g/p/54f5a1268b4a19ba6ffe4c35d65460f5.jpg_200x200q80.jpg_.webp</value>
      <webElementGuid>15a0f2e5-0d49-4a06-875f-e2b5266d1ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4l.searchlist.list.i40.8278319cesqsoz</value>
      <webElementGuid>7d0328dc-4113-4306-a1ba-35e6eac04e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;FWSEp&quot;]/div[@class=&quot;ant-row FrEdP css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-24 css-1bkhbmc app&quot;]/div[@class=&quot;ant-row css-1bkhbmc app&quot;]/div[@class=&quot;ant-col ant-col-20 ant-col-push-4 Jv5R8 css-1bkhbmc app&quot;]/div[@class=&quot;_17mcb&quot;]/div[@class=&quot;Bm3ON&quot;]/div[@class=&quot;Ms6aG MefHh&quot;]/div[@class=&quot;qmXQo&quot;]/div[@class=&quot;ICdUp&quot;]/div[@class=&quot;_95X4G&quot;]/a[1]/div[@class=&quot;picture-wrapper jBwCF&quot;]/img[1]</value>
      <webElementGuid>73e974b9-2e34-4bdd-b7ad-866b405f629d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@type='product']</value>
      <webElementGuid>246bc77c-003a-427d-979d-c1109ced4aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/div/div/div/div/div/a/div/img</value>
      <webElementGuid>a17ab0f6-3618-4ee3-aa33-bd9e1c897e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='1pc Pet Teaser Cat Toy Steel Wire Feather Interactive Cat Stick Training，Kitten Wand Toys with Beads Bells']</value>
      <webElementGuid>87f09279-fd3c-44e9-82fe-9e2083e12c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>9cb0dc7b-bdd5-402e-bb73-6fb2aec4ed06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@type = 'product' and @alt = '1pc Pet Teaser Cat Toy Steel Wire Feather Interactive Cat Stick Training，Kitten Wand Toys with Beads Bells' and @src = 'https://img.lazcdn.com/g/p/54f5a1268b4a19ba6ffe4c35d65460f5.jpg_200x200q80.jpg_.webp']</value>
      <webElementGuid>c8bf6608-5e15-4d7b-bf2c-229fd6da76fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
